### ISSUE TITLE
Edge foam not visible on Mobile

### ISSUE THREAD

**Issue by axel7083** [danielshervheim/Stylized-Water#1]
Hi,

I really love your shaders! But I have a little problem on the Android platform...

![Unity](https://user-images.githubusercontent.com/42176370/71735133-e0f91080-2e4d-11ea-9c2c-390e2fcf62ea.PNG)

I drag drop one of the "Stylized water material" on a surface. And everything was correct, until I changed the platform to Android, the foam edge doesn't render anymore.

I try to go in edit->Project Settings -> Quality and everythings to ultra (To found the right setting which control this aspect of the shader but I coundn't found it.

**Comment by danielshervheim** [comment]
I’ll take a look at this in the next few days - thanks for bringing to my attention!

**Comment by danielshervheim** [comment]
Thanks for your patience. I realized that on certain platforms the depth buffer is not enabled on the camera by default. I pushed an update which includes a script to explicitly enable it in `Assets/Stylized Water/EnableDepthBuffer.cs`. Just drag and drop that script on your camera and hopefully you should be good to go!
