### ISSUE TITLE
Amplify version would be awesome.

### ISSUE THREAD

**Issue by CowJuices** [danielshervheim/Stylized-Water#3]
This is easily the best water for the art style that i'm going for.

I'm breaking my head trying reverse engineering it to make it work in URP but my shader knowledge is super limited. So...

Is there any chance of you uploading the amplify version? Or a URP version?

Sorry for the inconvenience and thanks for your time.

**Comment by CowJuices** [comment]
Never mind I figure it out! haha!

**Comment by kekikcilerakin** [comment]
Would you mind sharing it with us?

**Comment by kekikcilerakin** [comment]
> 
> 
> Never mind I figure it out! haha!

Would you mind sharing it?
